## Main Config (https://github.com/r4g3baby/SimpleScore/blob/main/src/main/resources/config.yml)
# This is where you can customize some plugin settings and the default world scoreboards

# Config version (don't change this value)
version: 1

# Plugin language (supported: en, pt)
language: en

# Check for updates when the plugin starts
checkForUpdates: true

# Should we save player information (scoreboard force hidden/disabled)
savePlayerData: true

# Whether to apply placeholders asynchronously or not (disabling this might reduce performance)
asyncPlaceholders: true

# Enable this if you have other plugins that are overriding the scoreboard (requires server restart)
forceLegacy: false

# The format here is "<world name>: [ <list of scoreboards> ]"
# World Names:
# - Can use regex to match multiple worlds at once.
# - All world names are case-insensitive.
# - Worlds match from top to bottom, stopping at the first match.
# Scoreboards:
# - Scoreboards are defined in the "scoreboards.yml" file.
# - Scoreboard name is the same as defined in the scoreboards configuration node name.
# - The leftmost scoreboard in the list always takes priority.
worlds:
  # This will match all worlds starting with "world_" (e.g. world_nether, world_the_end)
  world_\w*: [ "customTime" ]
  # If player doesn't have permission to see the restricted scoreboard then it will display the example
  multiple: [ "restricted", "example" ]
  # This will match all worlds that haven't been defined above
  \w*: [ "example" ]
