# Config version (don't change this value)
version: 1

# Default scoreboard line update time in ticks (20 ticks = 1 second)
updateTime: 20

# Check for updates when the plugin starts
checkForUpdates: true

# Save which players have the scoreboard disabled
saveScoreboards: true

# Whether to apply placeholders asynchronously or not
asyncPlaceholders: true

# Enable this if you have other plugins that override the scoreboard (requires server restart)
forceLegacy: false

# The format here is "<world name>: [ <list of scoreboards> ]"
# World Names:
# - Can use regex to match multiple worlds at once.
# - All world names are case-insensitive.
# - Worlds match from top to bottom, stopping at the first match.
# Scoreboards:
# - Scoreboards are defined in the "scoreboards.yml" file.
# - Scoreboard name is the same as the configuration node name.
# - The leftmost scoreboard in the list always takes priority.
worlds:
  # This will match all worlds starting with "world_" (e.g. world_nether, world_the_end)
  world_\w*: [ "custom_time" ]
  # If player doesn't have permission to see the restricted scoreboard then it will display the example
  multiple: [ "restricted", "example" ]
  # This will match all worlds that haven't been defined above
  \w*: [ "example" ]
