# Default time in ticks for a score to stay on the scoreboard (20 ticks = 1 second)
UpdateTime: 20

# Save which players have the scoreboard disabled
SaveScoreboards: true

# Whether to apply placeholders asynchronously or not
AsyncPlaceholders: true

# Configure your scoreboards layout
Scoreboards:
  example:
    Titles:
      - "&7&LYour&6&lServer"
    Scores:
      13:
        - "&7&m+----------------+"
        - "&7&m------------------"
      12:
        - "&7» &6&lPlayer"
      11:
        - "    &7%player%"
      10:
        - ""
      9:
        - "&7» &6&lHealth"
      8:
        - "    %hearts%"
      7:
        - ""
      6:
        - "&7» &6&lWorld"
      5:
        - "    &7%world%"
      4:
        - ""
      3:
        - "&7» &6&lOnline Players"
      2:
        - "    &7%online% &6players"
      1:
        - "&7&m+----------------+"
        - "&7&m------------------"
  custom_time:
    Titles:
      - text: "&c100 ticks title"
        time: 100
      - text: "&a50 ticks title"
        time: 50
    Scores:
      6:
        - "&7You can set a per title or score time"
      5:
        - "&7instead of using the default value"
      4:
        - ""
      3:
        - text: "&7This will last for &810 seconds"
          time: 200
        - text: "&7while this only lasts for &85 seconds"
          time: 100
      2:
        - ""
      1:
        - "&aYour current world: &6%world%"
  restricted:
    Restricted: true
    Titles:
      - "&cRestricted Scoreboard"
    Scores:
      8:
        - ""
      7:
        - "&7Restricted scoreboards required the"
      6:
        - "&6simplescore.<scoreboard> &7permission."
      5:
        - ""
      4:
        - "&7You can see this scoreboard because"
      3:
        - "&7you have the following permission:"
      2:
        - "&6simplescore.restricted"
      1:
        - ""

# Set what scoreboards each world will be using
Worlds:
  # World names are case-insensitive
  world: [ "example" ]
  # This will match all worlds starting with "world_" (e.g. world_nether, world_the_end)
  world_\w*: [ "custom_time" ]
  # If player doesn't have permission to see the restricted scoreboard then it will display the example
  multiple: [ "restricted", "example" ]
