# Scoreboard update time in ticks (20 ticks = 1 second)
UpdateTime: 20

# Save which players have the scoreboard disabled
SaveScoreboards: true

# Per world scoreboards
Worlds:
  world:
    Titles:
    - "&cSimpleScore"
    - "&eSimpleScore"
    - "&aSimpleScore"
    - "&bSimpleScore"
    - "&5SimpleScore"
    Scores:
      6:
      - "&a&lOnline&8:"
      5:
      - "&7%online%&8/&7%maxplayers%"
      4:
      - ""
      3:
      - "&9&lSupports&8:"
      2:
      - "&bPlaceholderAPI"
      1:
      - "----------------"
  world_the_end:
    Titles:
    - "&cSimpleScore"
    - "&eSimpleScore"
    - "&aSimpleScore"
    - "&bSimpleScore"
    - "&5SimpleScore"
    Scores:
      2:
      - "&a&lWorld&8:"
      1:
      - "&7%world%"

# Shared scoreboards
Shared:
  world_the_end:
  - "world_nether"