name: ${project.name}
version: ${project.version}
main: com.r4g3baby.simplescore.SimpleScore
softdepend: [PlaceholderAPI]
authors: [R4G3_BABY]
description: "${project.description}"
website: ${project.url}

commands:
  SimpleScore:
    description: Manage plugin functionalities
    aliases: [ss]
    usage: /<command> <args>