name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar --build-cache

      - name: Generate changelog
        id: generate_changelog
        run: |
          git fetch --unshallow --tags
          tag=$(git tag --sort version:refname | tail -n 2 | head -n 1)
          if [ "$tag" ]; then
            changelog=$(git log --oneline --no-decorate $tag..HEAD)
          else
            changelog=$(git log --oneline --no-decorate)
          fi
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A' - }"
          changelog=" - ${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"

      - name: Get asset path
        id: get_asset_path
        run: |
          ASSET_PATH=$(ls build/libs/*.jar | head -n 1)
          echo "::set-output name=asset_path::$ASSET_PATH"

      - name: Create draft release
        id: create_draft_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}
          files: ${{ steps.get_asset_path.outputs.asset_path }}
          draft: true
